version: "3"

services:
  mongodb:
    build:      
      context: .
      dockerfile: Dockerfile-mongo
    ports:
      - "27017:27017"


  app:
    build: 
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - .:/usr/src/app
    links:
      - mongodb:mongodb