### Dockerfile for Ubuntu with MongoDB 3.2 running ###


# base image of ubuntu
FROM ubuntu:14.04


# Get MongoDB 3.2
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
	echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list && \
	apt-get update && \
	apt-get install --allow-unauthenticated -y mongodb-org && \
	apt-get clean

# Make data/db directory for Mongodb
VOLUME ["/data/db"]

# Set working directory
WORKDIR /data

# Expose ports for use of Mongodb
EXPOSE 27017
EXPOSE 28017

MAINTAINER nsmith@zam.com

# Run MongoDB
CMD ["mongod"]